import { Box, Typography, Divider } from "@mui/material";
import { useTheme, alpha } from "@mui/material/styles";
import { ArrowBackRounded, ShieldOutlined } from "@mui/icons-material";
import { useNavigate } from "react-router-dom";
import { T } from "../../theme/theme";

const LAST_UPDATED = "August 2, 2026";
const APP_NAME     = "PulseWatch";
const COMPANY      = "HivarSoft";
const CONTACT_EMAIL = "hello@hivarsoft.com";
const APP_URL      = "https://pulsewatch.hivarsoft.com";

export default function PrivacyPolicy() {
  const theme   = useTheme();
  const L       = theme.palette.mode === "light";
  const navigate = useNavigate();

  return (
    <Box sx={{ pt: 4, pb: 10, maxWidth: 780, mx: "auto" }}>
      {/* Back */}
      <Box
        onClick={() => navigate(-1)}
        sx={{
          display: "inline-flex", alignItems: "center", gap: 0.75,
          cursor: "pointer", mb: 4,
          color: "text.secondary",
          "&:hover": { color: "text.primary" },
          transition: "color 0.15s",
        }}
      >
        <ArrowBackRounded sx={{ fontSize: 14 }} />
        <Typography variant="caption" fontWeight={500}>Back</Typography>
      </Box>

      {/* Header */}
      <Box sx={{ display: "flex", alignItems: "flex-start", gap: 2, mb: 4 }}>
        <Box sx={{
          width: 44, height: 44, borderRadius: 2, flexShrink: 0,
          background: `linear-gradient(135deg, ${alpha(T.brand, L ? 0.12 : 0.22)}, ${alpha(T.brand, L ? 0.06 : 0.1)})`,
          border: `1px solid ${alpha(T.brand, L ? 0.18 : 0.28)}`,
          display: "flex", alignItems: "center", justifyContent: "center",
        }}>
          <ShieldOutlined sx={{ fontSize: 22, color: T.brand }} />
        </Box>
        <Box>
          <Typography variant="h2" color="text.primary" gutterBottom>Privacy Policy</Typography>
          <Typography variant="caption" color="text.disabled">
            Last updated: {LAST_UPDATED} · Effective immediately
          </Typography>
        </Box>
      </Box>

      <Box sx={{ p: 2.5, mb: 4, borderRadius: 2, backgroundColor: L ? T.brandSoft : alpha(T.brand, 0.1), border: `1px solid ${alpha(T.brand, 0.2)}` }}>
        <Typography variant="body2" color={L ? T.brand : "#a5b4fc"} sx={{ lineHeight: 1.7 }}>
          This Privacy Policy explains how {COMPANY} ("we", "us", or "our") collects, uses, and protects
          your personal information when you use {APP_NAME} ({APP_URL}). By using {APP_NAME} you agree to
          the practices described here.
        </Typography>
      </Box>

      <Section title="1. Information We Collect">
        <P>We collect the following categories of information:</P>
        <SubSection title="1.1 Account information (via OAuth)">
          <P>
            When you sign in through Google or GitHub, we receive from those providers only the
            information you have authorised them to share. This typically includes:
          </P>
          <ul>
            <Li>Your name (first and last)</Li>
            <Li>Your primary email address</Li>
            <Li>Your profile photo URL (optional — used as your avatar)</Li>
            <Li>A provider-specific user ID (used to link your account; never exposed publicly)</Li>
          </ul>
          <P>We do not receive or store your Google or GitHub password.</P>
        </SubSection>
        <SubSection title="1.2 Content you create">
          <P>
            Monitoring projects, service URLs, check configuration, alert channel credentials
            (e.g. SMTP credentials, Slack webhook URLs, Telegram bot tokens), and any other
            data you enter into {APP_NAME}.
          </P>
        </SubSection>
        <SubSection title="1.3 Usage and log data">
          <P>
            Server logs, check results, response times, uptime history, and error records
            generated by the monitoring system. This data is tied to your services, not sold or
            shared with third parties.
          </P>
        </SubSection>
        <SubSection title="1.4 Cookies and session tokens">
          <P>
            We set two cookies when you sign in:
          </P>
          <ul>
            <Li><strong>session_token</strong> — an HttpOnly, Secure cookie containing a short-lived
              (1-hour) JWT. This cookie is not readable by JavaScript and cannot be accessed by
              third-party scripts.
            </Li>
            <Li><strong>csrf_token</strong> — a readable cookie used for CSRF protection
              (double-submit pattern). It contains a random token matched server-side on every
              mutating request.
            </Li>
          </ul>
          <P>We do not use advertising cookies, tracking pixels, or third-party analytics.</P>
        </SubSection>
      </Section>

      <Section title="2. How We Use Your Information">
        <ul>
          <Li>To authenticate you and maintain your session securely</Li>
          <Li>To store and execute your uptime monitoring configuration</Li>
          <Li>To deliver alerts to the notification channels you configure</Li>
          <Li>To display historical uptime data, response time charts, and incident records</Li>
          <Li>To respond to support requests you send us</Li>
          <Li>To diagnose technical issues and maintain service reliability</Li>
        </ul>
        <P>
          We do not use your data for advertising, behavioural profiling, or any purpose
          unrelated to operating {APP_NAME}.
        </P>
      </Section>

      <Section title="3. Third-Party OAuth Providers">
        <P>
          {APP_NAME} uses Google and GitHub as identity providers. When you click
          "Continue with Google" or "Continue with GitHub", your browser is redirected to
          that provider's authentication servers. We do not see or handle your password.
        </P>
        <P>The data we receive is governed by:</P>
        <ul>
          <Li><strong>Google</strong>: <A href="https://policies.google.com/privacy">Google Privacy Policy</A></Li>
          <Li><strong>GitHub</strong>: <A href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub Privacy Statement</A></Li>
        </ul>
        <P>
          You can revoke {APP_NAME}'s access to your Google or GitHub account at any time from
          within those providers' security settings. Revoking access will not delete your
          {APP_NAME} account — you may delete it from <strong>Settings → Delete Account</strong>.
        </P>
      </Section>

      <Section title="4. Data Storage and Security">
        <P>
          Your data is stored in MongoDB Atlas (cloud-hosted database) with
          encryption at rest and in transit (TLS). Session tokens are transmitted only over
          HTTPS and stored in HttpOnly cookies to prevent XSS exposure.
        </P>
        <P>
          Alert channel credentials (SMTP passwords, webhook URLs, bot tokens) are stored
          in your account document. We do not encrypt these fields at the application layer
          beyond database-level encryption — do not store credentials that grant
          overly broad access.
        </P>
        <P>
          We apply reasonable technical and organisational security measures, but no system
          is completely secure. We will notify you promptly in the event of a data breach
          that affects your personal information.
        </P>
      </Section>

      <Section title="5. Data Retention">
        <P>
          We retain your data for as long as your account is active. If you delete your
          account, we delete your personal information and monitoring data within 30 days,
          except where retention is required by law or legitimate business need
          (e.g. server access logs retained for up to 90 days for security purposes).
        </P>
      </Section>

      <Section title="6. Sharing of Information">
        <P>
          We do not sell, rent, or trade your personal information. We may share data only in
          these limited circumstances:
        </P>
        <ul>
          <Li>
            <strong>Service providers</strong>: infrastructure providers (MongoDB Atlas, Redis
            hosting, email delivery services) who process data on our behalf under data
            processing agreements.
          </Li>
          <Li>
            <strong>Legal requirements</strong>: if required by applicable law, court order, or
            governmental authority.
          </Li>
          <Li>
            <strong>Business transfers</strong>: in the event of a merger or acquisition, your
            data may be transferred to the successor entity, who will be bound by this policy.
          </Li>
        </ul>
      </Section>

      <Section title="7. Your Rights">
        <P>Depending on your jurisdiction, you may have the right to:</P>
        <ul>
          <Li>Access the personal information we hold about you</Li>
          <Li>Correct inaccurate data (editable from <strong>Settings → Profile</strong>)</Li>
          <Li>Delete your account and associated data (<strong>Settings → Delete Account</strong>)</Li>
          <Li>Object to or restrict certain processing activities</Li>
          <Li>Data portability — export your monitoring data in JSON format (contact us)</Li>
        </ul>
        <P>
          To exercise any right not covered by self-service, email us at{" "}
          <A href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</A>.
        </P>
      </Section>

      <Section title="8. Children's Privacy">
        <P>
          {APP_NAME} is not directed at children under the age of 13. We do not knowingly
          collect personal information from children. If you believe a child has provided us
          with personal information, please contact us and we will delete it promptly.
        </P>
      </Section>

      <Section title="9. Changes to This Policy">
        <P>
          We may update this Privacy Policy from time to time. The "Last updated" date at the
          top will reflect the most recent revision. If we make material changes, we will
          notify you via email or a prominent notice within the application at least 14 days
          before the changes take effect.
        </P>
      </Section>

      <Section title="10. Contact Us" last>
        <P>
          If you have questions about this Privacy Policy or your data, please contact us:
        </P>
        <Box sx={{ p: 2, borderRadius: 1.5, backgroundColor: L ? T.n50 : alpha("#fff", 0.03), border: `1px solid ${theme.palette.divider}`, mt: 1 }}>
          <Typography variant="body2" color="text.primary" fontWeight={600}>{COMPANY}</Typography>
          <Typography variant="body2" color="text.secondary">
            Email: <A href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</A>
          </Typography>
          <Typography variant="body2" color="text.secondary">
            Website: <A href={APP_URL}>{APP_URL}</A>
          </Typography>
        </Box>
      </Section>
    </Box>
  );
}

// ── Shared sub-components ─────────────────────────────────────────────────────

function Section({ title, children, last }: { title: string; children: React.ReactNode; last?: boolean }) {
  const theme = useTheme();
  return (
    <Box sx={{ mb: last ? 0 : 5 }}>
      <Typography variant="h3" color="text.primary" sx={{ mb: 2 }}>{title}</Typography>
      {children}
      {!last && <Divider sx={{ mt: 4, borderColor: theme.palette.divider }} />}
    </Box>
  );
}

function SubSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <Box sx={{ mb: 2 }}>
      <Typography variant="subtitle2" color="text.primary" sx={{ mb: 1 }}>{title}</Typography>
      {children}
    </Box>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return (
    <Typography variant="body2" color="text.secondary" sx={{ mb: 1.5, lineHeight: 1.8 }}>
      {children}
    </Typography>
  );
}

function Li({ children }: { children: React.ReactNode }) {
  return (
    <Box component="li" sx={{ mb: 0.75 }}>
      <Typography variant="body2" color="text.secondary" sx={{ lineHeight: 1.8 }}>
        {children}
      </Typography>
    </Box>
  );
}

function A({ href, children }: { href: string; children: React.ReactNode }) {
  return (
    <Box
      component="a"
      href={href}
      target={href.startsWith("http") ? "_blank" : undefined}
      rel={href.startsWith("http") ? "noopener noreferrer" : undefined}
      sx={{ color: T.brand, textDecoration: "none", "&:hover": { textDecoration: "underline" } }}
    >
      {children}
    </Box>
  );
}
